# Wrangling - Looking Into How Parks in Paradise Compare to Cities of Similar Size

**I explore how the number of mobile home lots in Paradise compare to other cities with a similar population in 2018 (before the Camp Fire).** 

To answer the above question, I will use two notebooks. This one is focused on **wrangling and merging**. The notebook called 'MH_paradise_analysis' is focused on **data analysis**. 

There are two relevant datasets:
* List of mobile home parks permitted by the California Housing and Community Development Department. [Source.]('https://casas.hcd.ca.gov/casas/cmirMp/onlineQuery')
* Population by city and town in California. [Source.]('https://www.census.gov/programs-surveys/popest/technical-documentation/research/evaluation-estimates/2020-evaluation-estimates/2010s-cities-and-towns-total.html')

I will start by importing necessary libraries and creating an folder paths for the datasets I've cleaned and would like to import/export.

In [60]:
import pandas as pd 
import numpy as np
import os as os
import requests
from pprint import pprint

In [5]:
raw_dir = '/Users/kavishharjai/code/mh_paradise/raw/'
processed_outdir = '/Users/kavishharjai/code/mh_paradise/processed'

#### Cleaning MH dataset

In [6]:
list_of_parks = pd.read_csv(raw_dir + 'MH_parks.csv')
list_of_parks.head()

,Park Name,County,Park Identifier,Park Address,Fire Authority,Jurisdiction,MH Spaces,RV Lots W/Drains,RV Lots W/O Drains,Operated by,ADDRESS
0,SPANISH RANCH II,ALAMEDA,01-0001-MP,"121 RANCHERO WAY, HAYWARD, CA 94544, (510) 886...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",187.0,0.0,0.0,"HOMETOWN SPANISH RANCH, LLC, A DELAWARE LIMITE...","121 RANCHERO WAY, HAYWARD, CA 94544, (510) 886..."
1,GEORGIAN MANOR MHP,ALAMEDA,01-0003-MP,"1419 BUCKINGHAM WAY, HAYWARD, CA 94544, (510) ...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",265.0,0.0,0.0,"GEORGIAN MANOR MOBILEHOME PARK L P, 321 HARTZ ...","1419 BUCKINGHAM WAY, HAYWARD, CA 94544, (510) ..."
2,BAL TRAILER CT,ALAMEDA,01-0008-MP,"14831 BANCROFT AVE, SAN LEANDRO, CA 94578, (51...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",31.0,0.0,0.0,"PUEBLO SPRINGS MHP LTD, 10351 SANTA MONICA BLV...","14831 BANCROFT AVE, SAN LEANDRO, CA 94578, (51..."
3,VASCO MHP,ALAMEDA,01-0010-MP,"6539 S FRONT RD, LIVERMORE, CA 94550, (925) 44...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",50.0,21.0,0.0,"SOLOMON/MANDEL, EDWARD/GEORGE, PO BOX 406, ALA...","6539 S FRONT RD, LIVERMORE, CA 94550, (925) 44..."
4,AVALON MOBILE HOME PARK,ALAMEDA,01-0013-MP,"3970 CASTRO VALLEY BLVD, CASTRO VALLEY, CA 945...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",49.0,0.0,0.0,"AVALON MHP INC, 4061 EAST CASTRO VALLEY BLVD S...","3970 CASTRO VALLEY BLVD, CASTRO VALLEY, CA 945..."

**I will start by standardizing column names so there aren't spaces between words.**

In [7]:
list_of_parks = list_of_parks.rename(columns = {'Park Name': 'park_name',
                                                'County':'county',
                                              'Park Identifier': 'park_identifier', 
                                              'Park Address': 'park_address', 
                                              'MH Spaces': 'mh_spaces', 
                                              'Fire Authority': 'fire_authority', 
                                              'Jurisdiction': 'jurisdiction',
                                             'RV Lots W/Drains': 'rv_lots_drains',
                                             'RV Lots W/O Drains': 'rv_lots_no_drains',
                                             'Operated by': 'operated_by',
                                             'ADDRESS': 'operater_address'})

**In addition to mobile homes, this dataset contains information on RV Parks.**

**Since my analysis is focused on mobile homes, I will remove all observations where the value for MH_Spaces is 0.**

In [8]:
list_of_parks = list_of_parks[list_of_parks.mh_spaces != 0]

In [9]:
len(list_of_parks)

4668

**After filtering my dataframe, I wanted to check out what kind of data types there are and whether there are columns that are missing a bunch of values.**

In [10]:
list_of_parks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4668 entries, 0 to 5247
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   park_name          4668 non-null   object
 1   county             4668 non-null   object
 2   park_identifier    4668 non-null   object
 3   park_address       4668 non-null   object
 4   fire_authority     4668 non-null   object
 5   jurisdiction       4668 non-null   object
 6   mh_spaces          4667 non-null   float64
 7   rv_lots_drains     4667 non-null   float64
 8   rv_lots_no_drains  4667 non-null   float64
 9   operated_by        4664 non-null   object
 10  operater_address   4668 non-null   object
dtypes: float64(3), object(8)
memory usage: 437.6+ KB

**It looks pretty good, but since I'm invested in checking out the amount of spaces in each park, I want to probably get rid of the observation where the value of MH_Spaces is null.**

In [11]:
list_of_parks[list_of_parks['mh_spaces'].isnull()]

,park_name,county,park_identifier,park_address,fire_authority,jurisdiction,mh_spaces,rv_lots_drains,rv_lots_no_drains,operated_by,operater_address
2982,8456 BRADSHAW ROAD (S.O.P. W/OUT P.T.O.),SACRAMENTO,34-13586-MP,"8456 BRADSHAW ROAD, ELK GROVE, CA 95624","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",NaN,NaN,NaN,NaN,"8456 BRADSHAW ROAD, ELK GROVE, CA 95624"

In [12]:
list_of_parks = list_of_parks.drop(labels=2982, axis=0)

**The 'park_address' column annoyingly contains the park phone number. Let me split that column into separate entities, and then rejoin on all the address components. I ultimately will only be interested in the city column.**

In [13]:
list_of_parks['park_address'] = list_of_parks.park_address.str.title()

In [14]:
list_of_parks.head(10)

,park_name,county,park_identifier,park_address,fire_authority,jurisdiction,mh_spaces,rv_lots_drains,rv_lots_no_drains,operated_by,operater_address
0,SPANISH RANCH II,ALAMEDA,01-0001-MP,"121 Ranchero Way, Hayward, Ca 94544, (510) 886...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",187.0,0.0,0.0,"HOMETOWN SPANISH RANCH, LLC, A DELAWARE LIMITE...","121 RANCHERO WAY, HAYWARD, CA 94544, (510) 886..."
1,GEORGIAN MANOR MHP,ALAMEDA,01-0003-MP,"1419 Buckingham Way, Hayward, Ca 94544, (510) ...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",265.0,0.0,0.0,"GEORGIAN MANOR MOBILEHOME PARK L P, 321 HARTZ ...","1419 BUCKINGHAM WAY, HAYWARD, CA 94544, (510) ..."
2,BAL TRAILER CT,ALAMEDA,01-0008-MP,"14831 Bancroft Ave, San Leandro, Ca 94578, (51...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",31.0,0.0,0.0,"PUEBLO SPRINGS MHP LTD, 10351 SANTA MONICA BLV...","14831 BANCROFT AVE, SAN LEANDRO, CA 94578, (51..."
3,VASCO MHP,ALAMEDA,01-0010-MP,"6539 S Front Rd, Livermore, Ca 94550, (925) 44...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",50.0,21.0,0.0,"SOLOMON/MANDEL, EDWARD/GEORGE, PO BOX 406, ALA...","6539 S FRONT RD, LIVERMORE, CA 94550, (925) 44..."
4,AVALON MOBILE HOME PARK,ALAMEDA,01-0013-MP,"3970 Castro Valley Blvd, Castro Valley, Ca 945...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",49.0,0.0,0.0,"AVALON MHP INC, 4061 EAST CASTRO VALLEY BLVD S...","3970 CASTRO VALLEY BLVD, CASTRO VALLEY, CA 945..."
5,NEW ENGLAND VILLAGE,ALAMEDA,01-0015-MP,"940 New England Village Dr, Hayward, Ca 94544,...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",415.0,0.0,0.0,"BRANDENBURG STAEDLER & MOORE, 1122 WILLOW ST S...","940 NEW ENGLAND VILLAGE DR, HAYWARD, CA 94544,..."
6,DEL RIO MOBILE HOME,ALAMEDA,01-0016-MP,"1550 162Nd Ave, San Leandro, Ca 94578, (510) 2...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",52.0,0.0,0.0,"CALIFANO FAMILY TRUST, 1550 162ND AVENUE SPACE...","1550 162ND AVE, SAN LEANDRO, CA 94578, (510) 2..."
7,DEL VALLE MHP,ALAMEDA,01-0017-MP,"1148 Arroyo Rd, Livermore, Ca 94550, (510) 331...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",29.0,0.0,0.0,"ABBOUD FAMILY TRUST, PO BOX 3975, HAYWARD, CA ...","1148 ARROYO RD, LIVERMORE, CA 94550, (510) 331..."
8,BAYSHORE COMMONS,ALAMEDA,01-0023-MP,"1468 Grand Ave, San Leandro, Ca 94577, (510) 3...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",40.0,0.0,0.0,"SAN LEANDRO TRAILER PARK LLC, 6653 EMBARCADERO...","1468 GRAND AVE, SAN LEANDRO, CA 94577, (510) 3..."
9,FAIRVIEW TP,ALAMEDA,01-0024-MP,"785 Rose Ave, Pleasanton, Ca 94566, (925) 846-...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",14.0,8.0,0.0,"GIL, EDMUND, 2606 DERBY DR, SAN RAMON, CA 94583","785 ROSE AVE, PLEASANTON, CA 94566, (925) 846-..."

In [15]:
list_of_parks[['num_st', 'city', 'state', 'phone_num']] = list_of_parks['park_address'].str.split(',', n = 3, expand=True)
#the park_address column in the OG dataframe contains the phone number for the park, which would confuse the geocoding system. Here, I separate that column on comma delimiter.

In [16]:
list_of_parks.head(10)

,park_name,county,park_identifier,park_address,fire_authority,jurisdiction,mh_spaces,rv_lots_drains,rv_lots_no_drains,operated_by,operater_address,num_st,city,state,phone_num
0,SPANISH RANCH II,ALAMEDA,01-0001-MP,"121 Ranchero Way, Hayward, Ca 94544, (510) 886...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",187.0,0.0,0.0,"HOMETOWN SPANISH RANCH, LLC, A DELAWARE LIMITE...","121 RANCHERO WAY, HAYWARD, CA 94544, (510) 886...",121 Ranchero Way,Hayward,Ca 94544,(510) 886-4646
1,GEORGIAN MANOR MHP,ALAMEDA,01-0003-MP,"1419 Buckingham Way, Hayward, Ca 94544, (510) ...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",265.0,0.0,0.0,"GEORGIAN MANOR MOBILEHOME PARK L P, 321 HARTZ ...","1419 BUCKINGHAM WAY, HAYWARD, CA 94544, (510) ...",1419 Buckingham Way,Hayward,Ca 94544,(510) 785-2212
2,BAL TRAILER CT,ALAMEDA,01-0008-MP,"14831 Bancroft Ave, San Leandro, Ca 94578, (51...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",31.0,0.0,0.0,"PUEBLO SPRINGS MHP LTD, 10351 SANTA MONICA BLV...","14831 BANCROFT AVE, SAN LEANDRO, CA 94578, (51...",14831 Bancroft Ave,San Leandro,Ca 94578,(510) 352-8152
3,VASCO MHP,ALAMEDA,01-0010-MP,"6539 S Front Rd, Livermore, Ca 94550, (925) 44...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",50.0,21.0,0.0,"SOLOMON/MANDEL, EDWARD/GEORGE, PO BOX 406, ALA...","6539 S FRONT RD, LIVERMORE, CA 94550, (925) 44...",6539 S Front Rd,Livermore,Ca 94550,(925) 447-0758
4,AVALON MOBILE HOME PARK,ALAMEDA,01-0013-MP,"3970 Castro Valley Blvd, Castro Valley, Ca 945...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",49.0,0.0,0.0,"AVALON MHP INC, 4061 EAST CASTRO VALLEY BLVD S...","3970 CASTRO VALLEY BLVD, CASTRO VALLEY, CA 945...",3970 Castro Valley Blvd,Castro Valley,Ca 94546,(510) 537-4815
5,NEW ENGLAND VILLAGE,ALAMEDA,01-0015-MP,"940 New England Village Dr, Hayward, Ca 94544,...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",415.0,0.0,0.0,"BRANDENBURG STAEDLER & MOORE, 1122 WILLOW ST S...","940 NEW ENGLAND VILLAGE DR, HAYWARD, CA 94544,...",940 New England Village Dr,Hayward,Ca 94544,(510) 785-4511
6,DEL RIO MOBILE HOME,ALAMEDA,01-0016-MP,"1550 162Nd Ave, San Leandro, Ca 94578, (510) 2...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",52.0,0.0,0.0,"CALIFANO FAMILY TRUST, 1550 162ND AVENUE SPACE...","1550 162ND AVE, SAN LEANDRO, CA 94578, (510) 2...",1550 162Nd Ave,San Leandro,Ca 94578,(510) 278-8810
7,DEL VALLE MHP,ALAMEDA,01-0017-MP,"1148 Arroyo Rd, Livermore, Ca 94550, (510) 331...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",29.0,0.0,0.0,"ABBOUD FAMILY TRUST, PO BOX 3975, HAYWARD, CA ...","1148 ARROYO RD, LIVERMORE, CA 94550, (510) 331...",1148 Arroyo Rd,Livermore,Ca 94550,(510) 331-2000
8,BAYSHORE COMMONS,ALAMEDA,01-0023-MP,"1468 Grand Ave, San Leandro, Ca 94577, (510) 3...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",40.0,0.0,0.0,"SAN LEANDRO TRAILER PARK LLC, 6653 EMBARCADERO...","1468 GRAND AVE, SAN LEANDRO, CA 94577, (510) 3...",1468 Grand Ave,San Leandro,Ca 94577,(510) 351-5950
9,FAIRVIEW TP,ALAMEDA,01-0024-MP,"785 Rose Ave, Pleasanton, Ca 94566, (925) 846-...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...","HCD - NORTHERN AREA OFFICE, 9342 TECH CENTER D...",14.0,8.0,0.0,"GIL, EDMUND, 2606 DERBY DR, SAN RAMON, CA 94583","785 ROSE AVE, PLEASANTON, CA 94566, (925) 846-...",785 Rose Ave,Pleasanton,Ca 94566,(925) 846-5074

In [17]:
list_of_parks['city'] = list_of_parks['city'].str.lstrip(' ')

In [18]:
list_of_parks[['state_only', 'zip']] = list_of_parks['state'].str.split(expand=True)

In [19]:
list_of_parks['state_only'] = list_of_parks.state_only.str.upper()

In [20]:
list_of_parks["updated_address"] = list_of_parks["num_st"] +","+ list_of_parks["city"] + "," + list_of_parks["state"]
#combine the relevant address columns into an updated address column

**Just in case it ends up being helpful, I will create a column of mobile home lot ranges.**

In [21]:
bins = [0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500, np.inf]
labels = ["'0-50'",
          "'51-100'", 
          "'101-150'", 
          "'151-200'",
          "'201-250'",
          "'251-300'",
          "'301-350'",
          "'351-400'",
          "401-450'",
          "451-500'",
          "'>500'"]
list_of_parks["mh_spaces_ranges"] = pd.cut(list_of_parks["mh_spaces"], bins=bins, labels=labels)
#create new column with range of MH_Spaces

**Next, I will explore some of the data fields. First off, it looks like there are 57 counties which make sense. I will go through them and ensure there are no duplicates.**

In [22]:
list_of_parks["county"] = list_of_parks["county"].str.lower()

In [23]:
list_of_parks.county.nunique()

57

In [24]:
list_of_parks.county.unique()

array(['alameda', 'alpine', 'amador', 'butte', 'calaveras', 'colusa',
       'contra costa', 'del norte', 'el dorado', 'fresno', 'glenn',
       'humboldt', 'imperial', 'los angeles', 'riverside', 'inyo', 'kern',
       'kings', 'lake', 'lassen', 'madera', 'marin', 'mariposa',
       'tuolumne', 'merced', 'mendocino', 'modoc', 'mono', 'monterey',
       'santa cruz', 'napa', 'nevada', 'placer', 'orange', 'plumas',
       'sacramento', 'solano', 'san benito', 'san bernardino',
       'san diego', 'san joaquin', 'san luis obispo', 'san mateo',
       'santa barbara', 'santa clara', 'shasta', 'siskiyou', 'sierra',
       'sonoma', 'stanislaus', 'sutter', 'yolo', 'tehama', 'trinity',
       'tulare', 'ventura', 'yuba'], dtype=object)

**I'll also explore the city names, of which there are many.**

In [25]:
list_of_parks.city.unique()

array(['Hayward', 'San Leandro', 'Livermore', 'Castro Valley',
       'Pleasanton', 'Oakland', 'Union City', 'Fremont', 'Markleeville',
       'Pine Grove', 'Ione', 'Pioneer', 'Martell', 'Jackson', 'Plymouth',
       'Oroville', 'Paradise', 'Chico', 'Gridley', 'Palermo',
       'Forbestown', 'Forest Ranch', 'Cohasset', 'Biggs', 'Magalia',
       'West Point', 'San Andreas', 'Avery', 'Valley Springs',
       'Angels Camp', 'Copperopolis', 'Dorrington', 'Railroad Flat',
       'Murphys', 'Williams', 'Colusa', 'Grimes', 'Maxwell', 'Arbuckle',
       '3 Mi E Of Williams', 'Stonyford', 'Oakley', 'San Pablo',
       'Bay Point', 'Antioch', 'El Sobrante', 'Pittsburg',
       'Bethel Island', 'Brentwood', 'Pacheco', 'Rodeo', 'Concord',
       'Pleasant Hill', 'Byron', 'Clayton', 'Crescent City',
       'Smith River', 'Klamath', 'Gasquet', 'Diamond Springs',
       'South Lake Tahoe', 'Placerville', 'Pollock Pines',
       'Shingle Springs', 'Camino', 'El Dorado', 'Georgetown', 'Lotus',
       'El Dorado Hills', 'Somerset', 'Pilot Hill', 'Cameron Park',
       'Kelsey', 'Fresno', 'Mendota', 'Sanger', 'Coalinga', 'San Joaquin',
       'Kerman', 'Selma', 'Clovis', 'Firebaugh', 'Lakeshore', 'Huron',
       'Piedra', 'Riverdale', 'Friant', 'Shaver Lake', 'Fowler',
       'Auberry', 'Parlier', 'Kingsburg', 'Reedley', 'Dunlap', 'Orland',
       'Glenn', 'Willows', 'Elk Creek', '#9', 'Hamilton City', 'Redway',
       'Eureka', 'Fortuna', 'Willow Creek', 'Mckinleyville', 'Miranda',
       'Myers Flat', 'Orick', 'Rio Dell', 'Arcata', 'Trinidad', 'Loleta',
       'Orleans', 'Phillipsville', 'Hydesville', 'Bridgeville',
       'Carlotta', 'Hwy 96', 'Garberville', 'Redcrest', 'Whitethorn',
       'Ferndale', 'Weott', 'Scotia', 'Blue Lake', 'Palo Verde',
       'El Centro', 'Holtville', 'Bard', 'Hawthorne', 'Niland', 'Brawley',
       'Winterhaven', 'Desert Shores', 'Ocotillo', 'Calexico',
       'Salton City', 'Heber', 'Seeley', 'Independence', 'Lone Pine',
       'Bishop', 'Death Valley', 'Shoshone', 'Olancha', 'Big Pine',
       'Tecopa', 'Cartago', 'Bakersfield', 'Shafter', 'Ridgecrest',
       'Kernville', 'Delano', 'Tehachapi', 'Arvin', 'Inyokern',
       'Lake Isabella', 'Rosamond', 'Lamont', 'Boron', 'Wasco', 'Haddad',
       'Wofford Heights', 'Mojave', 'Aerial Acres', 'Bodfish', 'Taft',
       'Lebec', 'Lost Hills', 'Frazier Park', '8 Mi E Of Taft',
       'Di Giorgio', 'California City', 'Avenal', 'Corcoran', 'Hanford',
       'Lemoore', 'Lucerne', 'Clearlake', 'Glenhaven', 'Clearlake Oaks',
       'Kelseyville', 'Nice', 'Lakeport', 'Lower Lake', 'Upper Lake',
       'Middletown', 'Cobb', 'Clearlake Park', 'Loch Lomond', 'Milford',
       'Litchfield', 'Susanville', 'Doyle', 'Janesville', 'Herlong',
       '2Mi N Of Milford', 'Bieber', 'Westwood', 'Lawndale', 'Cudahy',
       'Bell Gardens', 'El Monte', 'Acton', 'S El Monte', 'Inglewood',
       'Gardena', 'Compton', 'Lake Hughes', 'Azusa', 'Culver City',
       'Palmdale', 'Bellflower', 'Los Angeles', 'Paramount', 'Pomona',
       'Topanga', 'Santa Clarita', 'Pico Rivera', 'Norwalk', 'Llano',
       'Whittier', 'Santa Fe Springs', 'Hermosa Beach', 'Covina',
       'La Puente', 'Glendora', 'Lomita', 'La Verne', 'Rosemead',
       'Baldwin Park', 'Lakewood', 'Carson', 'Monterey Park',
       'Leona Valley', 'Downey', 'Bell', 'Malibu', 'Huntington Park',
       'Torrance', 'Lancaster', 'Duarte', 'Santa Monica', 'Monrovia',
       'Agua Dulce', 'Pearblossom', 'Littlerock', 'Montebello',
       'Canyon Country', 'Sylmar', 'Lynwood', 'Hawaiian Gardens',
       'Long Beach', 'Newhall', 'Rowland Heights', 'Harbor City',
       'San Dimas', 'Saugus', 'Pacific Palisades', 'Van Nuys', 'Pacoima',
       'Chatsworth', 'North Hollywood', 'Northridge', "Mgr'S Off",
       'Sun Valley', 'Sunland', 'Reseda', 'Wilmington', 'South Gate',
       'Castaic', 'Mission Hills', 'Woodland Hills', 'Artesia',
       'Canoga Park', 'Agoura', 'Avalon', 'Calabasas', 'West Covina',
       'Hacienda Heights', 'San Pedro', 'La Mirada', 'Lake View Terrace',
       'Redondo Beach', 'Westlake Village', 'San Fernando', 'West Hills',
       'Diamond Bar', 'Walnut', 'Kagel Canyon', 'Chowchilla',
       'North Fork', 'Bass Lake', 'Madera', 'Oakhurst', 'Coarsegold',
       'Novato', 'Forest Knolls', 'Larkspur', 'Dillon Beach', 'Greenbrae',
       'San Rafael', 'Catheys Valley', 'Groveland', 'Coulterville',
       'Mariposa', 'Snelling', 'Midpines', 'Calpella', 'Ukiah',
       'Redwood Valley', 'Fort Bragg', 'Willits', 'Philo', 'Covelo',
       'Gualala', 'Albion', 'Mendocino', 'Laytonville', 'Leggett',
       'Boonville', 'Potter Valley', 'Branscomb', 'Manchester',
       'Point Arena', 'Little River', 'Atwater', 'Gustine', 'Los Banos',
       'Merced', 'Winton', 'Dos Palos', 'Santa Nella', 'El Nido', 'Delhi',
       'Hilmar', 'Livingston', 'Likely', 'Alturas', 'Cedarville', 'Adin',
       'Bridgeport', 'Lee Vining', 'June Lake', 'Mammoth Lakes', 'Walker',
       'Crowley Lake', 'Benton', 'Topaz', 'Chalfant Valley', 'Gonzales',
       'Salinas', 'Lockwood', 'Seaside', 'Soledad', 'Watsonville',
       'Big Sur', 'San Ardo', 'King City', 'Greenfield', 'Castroville',
       'Marina', 'Carmel Valley', 'Moss Landing', 'Pacific Grove',
       'Bradley', 'Napa', 'Saint Helena', 'Angwin', 'Calistoga',
       'American Canyon', 'Yountville', 'Grass Valley', 'Nevada City',
       'Truckee', 'Rough And Ready', 'Washington', 'Penn Valley',
       'Auburn', 'N San Juan', 'Costa Mesa', 'Fullerton', 'Cypress',
       'La Habra', 'Tustin', 'Midway City', 'Garden Grove', 'Anaheim',
       'Huntington Beach', 'San Clemente', 'Laguna Beach', 'Santa Ana',
       'Newport Beach', 'Dana Point', 'Placentia', 'Brea', 'Orange',
       'Stanton', 'Westminster', 'San Juan Capistrano', 'Buena Park',
       'Fountain Valley', 'Los Alamitos', 'Irvine', 'Laguna Hills',
       'Yorba Linda', 'Lake Forest', 'El Toro', 'Silverado', 'Seal Beach',
       'Roseville', 'Rocklin', 'Kings Beach', 'Foresthill', 'Granite Bay',
       'Tahoe Vista', 'Newcastle', 'Lincoln', 'Weimar', 'Colfax',
       'Meadow Vista', 'Loomis', 'Sheridan', 'Belden', 'Chester',
       'Quincy', 'Greenville', 'Prattville', 'Lake Almanor', 'Canyon Dam',
       'Chilcoot', 'Portola', 'Vinton', 'Twain', 'Cromberg',
       'Taylorsville', 'East Quincy', 'Graeagle', 'Crescent Mills',
       'East Shore', '177 Leonard Ave', 'Blairsden', 'Meadow Valley',
       'Beckwourth', 'Coachella', 'Riverside', 'Banning', 'Blythe',
       'Hemet', 'Desert Hot Springs', 'Lake Elsinore', 'Indio',
       'San Jacinto', 'Thermal', 'Beaumont', 'Corona', 'Idyllwild',
       'Palm Springs', 'La Quinta', 'Mira Loma', 'Cathedral City',
       'Office', 'N Palm Springs', 'Palm Desert', 'Rubidoux',
       'Moreno Valley', 'Perris', 'Mecca', 'Calimesa', 'Cherry Valley',
       'Jurupa Valley', 'Quail Valley', 'Desert Center', 'Eastvale',
       'Temecula', 'Sun City', 'Murrieta', 'Mountain Center',
       'Canyon Lake', 'Chiriaco Summit', 'Wildomar', 'Anza',
       'Rancho Mirage', 'Menifee', 'Orangevale', 'Galt', 'Walnut Grove',
       'Sacramento', 'Citrus Heights', 'Folsom', 'N Highlands', 'Isleton',
       'Elk Grove', 'Rancho Cordova', 'Rio Vista', 'Hood', 'Antelope',
       'Wilton', 'Rancho Murieta', 'Hollister', 'San Juan Bautista',
       'Paicines', 'Aromas', 'Adelanto', 'Fontana', 'Twentynine Palms',
       'Parker Dam', 'Bloomington', 'San Bernardino', 'Mentone', 'Baker',
       'Big Bear Lake', 'Needles', 'Barstow', 'Ontario', 'Hinkley',
       'Victorville', 'Daggett', 'Lake Arrowhead', 'Fawnskin',
       'Loma Linda', 'Oro Grande', 'Colton', 'Highland', 'Montclair',
       'Chino', 'Redlands', 'Joshua Tree', 'Rialto', 'Earp', 'Yucaipa',
       'Yucca Valley', 'Lucerne Valley', 'Apple Valley', 'Hesperia',
       'Crestline', 'Space #1', 'Morongo Valley', 'Grand Terrace',
       'Wrightwood', 'Box 435', 'Rancho Cucamonga', 'Lytle Creek',
       'Yermo', 'Havasu Lake', 'Upland', 'Angelus Oaks',
       'Newberry Springs', 'Chino Hills', 'Big Bear City', 'Phelan',
       'Trona', 'Cadiz', 'El Cajon', 'Santa Ysabel', 'Julian',
       'Chula Vista', 'Borrego Springs', 'Vista', 'Encinitas', 'La Mesa',
       'Ramona', 'San Diego', 'Leucadia', 'Fallbrook', 'San Ysidro',
       'National City', 'Imperial Beach', 'Escondido', 'Boulevard',
       'Lakeside', 'Lemon Grove', 'Valley Center', 'Oceanside',
       'Warner Springs', 'Santee', 'Jamul', 'Jacumba', 'San Marcos',
       'Mount Laguna', 'Guatay', 'Poway', 'Suite A', 'Business',
       'Spring Valley', '4 M W Of Lk Henshaw', 'Potrero', 'Alpine',
       'Dulzura', 'Carlsbad', 'Bostonia', 'Pauma Valley', 'Rainbow',
       'Bonita', 'Bonsall', 'Stockton', 'Vernalis', 'Escalon', 'Lodi',
       'French Camp', 'Tracy', 'Holt', 'Acampo', 'Manteca', 'Lockeford',
       'Thornton', 'Woodbridge', 'Victor', 'Lathrop', 'Ripon', 'Banta',
       'Baywood Park', 'San Miguel', 'Morro Bay', 'Arroyo Grande',
       'Atascadero', 'Paso Robles', 'Cambria', 'San Luis Obispo',
       'Templeton', 'Grover Beach', 'Cayucos', 'Oceano', 'San Simeon',
       'Nipomo', 'Halcyon', 'Santa Margarita', 'Los Osos', 'Pismo Beach',
       'Creston', 'Avila Beach', 'Brisbane', 'Belmont', 'East Palo Alto',
       'Half Moon Bay', 'Redwood City', 'S San Francisco', 'Pacifica',
       'Moss Beach', 'La Honda', 'Daly City', 'Santa Maria',
       'Carpinteria', 'Santa Barbara', 'Lompoc', 'Santa Ynez', 'Orcutt',
       'Goleta', 'Summerland', 'Los Alamos', 'Buellton', 'Solvang',
       'Palo Alto', 'San Jose', 'Sunnyvale', 'Morgan Hill', 'Gilroy',
       'Los Gatos', 'Mountain View', 'Milpitas', 'Campbell', 'Santa Cruz',
       'Aptos', 'Freedom', 'Scotts Valley', 'Soquel', 'Boulder Creek',
       'Ben Lomond', 'Capitola', 'Felton', 'Cottonwood', 'Anderson',
       'Redding', 'Big Bend', 'Mcarthur', 'Lakehead', 'Whitmore',
       'Burney', 'Dunsmuir', 'Shasta Lake', 'Shingletown',
       'Round Mountain', 'Castella', 'Shasta', '1/2 M/W Of Shingletown',
       'Cassel', 'Palo Cedro', 'French Gulch', 'Mccloud',
       'Montgomery Creek', 'Calpine', 'Loyalton', 'Downieville',
       'Happy Camp', 'Tulelake', 'Etna', 'Yreka', 'Klamath River',
       'Dorris', 'Weed', 'Seiad Valley', 'Hornbrook', 'Mount Shasta',
       'Montague', 'Callahan', 'Gazelle', 'Fort Jones', 'Somes Bar',
       'Benicia', 'Vacaville', 'Fairfield', 'Suisun City', 'Vallejo',
       'Dixon', 'Bodega Bay', 'Santa Rosa', 'Sonoma', 'Penngrove',
       'Healdsburg', 'Monte Rio', 'Cloverdale', 'Cotati', 'Windsor',
       'Petaluma', 'Sebastopol', 'Boyes Springs', 'Forestville', 'Jenner',
       'Rohnert Park', 'Guerneville', 'Duncans Mills', 'Riverbank',
       'Hughson', 'Modesto', 'Ceres', 'La Grange', 'Turlock',
       'Crows Landing', 'Empire', 'Denair', 'Oakdale', 'Newman',
       'Patterson', 'Waterford', 'Keyes', 'Yuba City', 'Knights Landing',
       'Live Oak', 'Meridian', 'Robbins', 'Hwy 113', 'Nicolaus',
       'Red Bluff', 'Corning', 'Los Molinos', 'Gerber', 'Manton',
       'Mill Creek', 'Hayfork', 'Mad River', 'Weaverville',
       'Douglas City', 'Lewiston', 'Helena', 'Salyer', 'Ruth',
       '1/2 Mi N Trinity Center', 'Big Bar', 'Burnt Ranch',
       '1/2 Mi West Of Big Bar', 'Junction City', 'Wildwood', 'Hyampom',
       'Porterville', 'Dinuba', 'Lindsay', 'Visalia', 'Terra Bella',
       'Exeter', 'Tulare', 'Pixley', 'Springville', 'Three Rivers',
       'Woodlake', 'Strathmore', 'California Hot Springs', 'Badger', '',
       'Orosi', 'Sonora', 'Jamestown', 'Columbia', 'Twain Harte',
       'Mi Wuk Village', 'Big Oak Flat', 'Oxnard', 'Ventura',
       'Thousand Oaks', 'Santa Paula', 'Ojai', 'Simi Valley', 'Piru',
       'Fillmore', 'Newbury Park', 'Oak View', 'Camarillo', 'Moorpark',
       'West Sacramento', 'Davis', 'Winters', 'Woodland', 'Esparto',
       'Dunnigan', 'Marysville', 'Wheatland', 'Camptonville', 'Challenge',
       'Brownsville', 'Olivehurst', 'Dobbins', 'Oregon House'],
      dtype=object)

In [26]:
list_of_parks.city.nunique()

821

**There are some funky values in this column, like those that give a distance from the highway or one that is just named '#9.' Those might be an outcome of the split I did on the original address column.**

**Next, I'll filter this dataframe down so it only contains columns necessary to my analysis.**

In [27]:
list_of_parks_filtered = list_of_parks[['park_name',
                                        'mh_spaces',
                                        'city']]

In [28]:
list_of_parks_filtered.head()

                 park_name  mh_spaces           city
0         SPANISH RANCH II      187.0        Hayward
1       GEORGIAN MANOR MHP      265.0        Hayward
2           BAL TRAILER CT       31.0    San Leandro
3                VASCO MHP       50.0      Livermore
4  AVALON MOBILE HOME PARK       49.0  Castro Valley

**The last thing I'll do is apply a groupby to the dataframe so there are columns for each city and the amount of MH spaces in each city.**

In [29]:
list_of_parks_analysis = list_of_parks_filtered.groupby('city').mh_spaces.sum().reset_index().sort_values('mh_spaces')

In [30]:
list_of_parks_analysis

            city  mh_spaces
128  Canyon Lake        1.0
33        Aromas        1.0
448      Magalia        1.0
594  Point Arena        1.0
420  Loch Lomond        1.0
..           ...        ...
653    San Diego     4747.0
232     El Cajon     5359.0
644   Sacramento     6729.0
322        Hemet     6987.0
658     San Jose    10667.0

[821 rows x 2 columns]

**Export dataframe as CSV.**

In [31]:
outname = 'mh_parks_analysis.csv'
fullname = os.path.join(processed_outdir, outname)
list_of_parks_analysis.to_csv(fullname)

### Cleaning population dataset

In [32]:
census_pop_est = pd.read_csv(raw_dir + 'california_pop_est.csv', encoding='latin1') #latin1 bc csv isn't utf-8 encoded
census_pop_est

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,...,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE042020,POPESTIMATE2020
0,40,6,0,0,0,0,0,A,California,California,...,37944551,38253768,38586706,38904296,39149186,39337785,39437463,39437610,39418894,39368078
1,162,6,0,296,0,0,0,A,Adelanto city,California,...,31222,31414,32745,33376,33484,34309,34411,34506,34540,34537
2,162,6,0,394,0,0,0,A,Agoura Hills city,California,...,20484,20537,20585,20634,20586,20471,20307,20103,19954,19881
3,162,6,0,562,0,0,0,A,Alameda city,California,...,75750,76616,77646,78997,80023,80178,80196,79813,79170,78841
4,162,6,0,674,0,0,0,A,Albany city,California,...,19041,19286,19557,19827,19958,20168,20352,20257,20110,20031
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1072,157,6,113,99990,0,0,1,F,Balance of Yolo County,California,...,26132,26480,26138,26964,28477,29296,29636,29772,29402,29337
1073,50,6,115,0,0,0,0,A,Yuba County,California,...,72770,73082,73527,74039,74920,76575,77418,78549,79800,80160
1074,157,6,115,46170,0,0,1,A,Marysville city,California,...,12119,12169,12200,12212,12259,12453,12499,12526,12590,12594
1075,157,6,115,85012,0,0,1,A,Wheatland city,California,...,3525,3526,3533,3539,3559,3622,3647,3654,3665,3666
1076,157,6,115,99990,0,0,1,F,Balance of Yuba County,California,...,57126,57387,57794,58288,59102,60500,61272,62369,63545,63900

In [33]:
census_pop_est.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1077 entries, 0 to 1076
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SUMLEV             1077 non-null   int64
 1   STATE              1077 non-null   int64
 2   COUNTY             1077 non-null   int64
 3   PLACE              1077 non-null   int64
 4   COUSUB             1077 non-null   int64
 5   CONCIT             1077 non-null   int64
 6   PRIMGEO_FLAG       1077 non-null   int64
 7   FUNCSTAT           1077 non-null   object
 8   NAME               1077 non-null   object
 9   STNAME             1077 non-null   object
 10  CENSUS2010POP      1077 non-null   object
 11  ESTIMATESBASE2010  1077 non-null   int64
 12  POPESTIMATE2010    1077 non-null   int64
 13  POPESTIMATE2011    1077 non-null   int64
 14  POPESTIMATE2012    1077 non-null   int64
 15  POPESTIMATE2013    1077 non-null   int64
 16  POPESTIMATE2014    1077 non-null   int64
 17  POPESTIMATE2015    1077 non-null   int64
 18  POPESTIMATE2016    1077 non-null   int64
 19  POPESTIMATE2017    1077 non-null   int64
 20  POPESTIMATE2018    1077 non-null   int64
 21  POPESTIMATE2019    1077 non-null   int64
 22  POPESTIMATE042020  1077 non-null   int64
 23  POPESTIMATE2020    1077 non-null   int64
dtypes: int64(20), object(4)
memory usage: 202.1+ KB

In [34]:
census_pop_est.columns= census_pop_est.columns.str.lower()

In [35]:
census_pop_est.name.nunique()

595

**This is confusing - there are only 595 unique values under the name column but 1,077 observations. 595*2 != 1,077, so it's not as simple as there being duplicates of each observation. I'll try to figure out what's going on in the following cells.**

In [36]:
census_pop_est[census_pop_est.name.str.contains(" city| town")].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 964 entries, 1 to 1075
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sumlev             964 non-null    int64
 1   state              964 non-null    int64
 2   county             964 non-null    int64
 3   place              964 non-null    int64
 4   cousub             964 non-null    int64
 5   concit             964 non-null    int64
 6   primgeo_flag       964 non-null    int64
 7   funcstat           964 non-null    object
 8   name               964 non-null    object
 9   stname             964 non-null    object
 10  census2010pop      964 non-null    object
 11  estimatesbase2010  964 non-null    int64
 12  popestimate2010    964 non-null    int64
 13  popestimate2011    964 non-null    int64
 14  popestimate2012    964 non-null    int64
 15  popestimate2013    964 non-null    int64
 16  popestimate2014    964 non-null    int64
 17  popestimate2015    964 non-null    int64
 18  popestimate2016    964 non-null    int64
 19  popestimate2017    964 non-null    int64
 20  popestimate2018    964 non-null    int64
 21  popestimate2019    964 non-null    int64
 22  popestimate042020  964 non-null    int64
 23  popestimate2020    964 non-null    int64
dtypes: int64(20), object(4)
memory usage: 188.3+ KB

**Ok, so there are 964 entries under name that have city or town in the name.**

In [37]:
census_pop_est[census_pop_est.name.str.contains(" County")].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112 entries, 483 to 1076
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sumlev             112 non-null    int64
 1   state              112 non-null    int64
 2   county             112 non-null    int64
 3   place              112 non-null    int64
 4   cousub             112 non-null    int64
 5   concit             112 non-null    int64
 6   primgeo_flag       112 non-null    int64
 7   funcstat           112 non-null    object
 8   name               112 non-null    object
 9   stname             112 non-null    object
 10  census2010pop      112 non-null    object
 11  estimatesbase2010  112 non-null    int64
 12  popestimate2010    112 non-null    int64
 13  popestimate2011    112 non-null    int64
 14  popestimate2012    112 non-null    int64
 15  popestimate2013    112 non-null    int64
 16  popestimate2014    112 non-null    int64
 17  popestimate2015    112 non-null    int64
 18  popestimate2016    112 non-null    int64
 19  popestimate2017    112 non-null    int64
 20  popestimate2018    112 non-null    int64
 21  popestimate2019    112 non-null    int64
 22  popestimate042020  112 non-null    int64
 23  popestimate2020    112 non-null    int64
dtypes: int64(20), object(4)
memory usage: 21.9+ KB

**There are 112 observations that have the word ' County' in name column.**

**112 + 964 = 1,076. Then there's one row for all of California, which equals the total amount of rows in the whole dataset. So I think I can confidently extract cities from this dataset by trying to find those with city or town in them.**

In [38]:
ca_cities = census_pop_est[census_pop_est.name.str.contains(" city| town")]

In [39]:
ca_cities.name.nunique()

482

**Ok so the number of unique names in the cities is half of the entries in the cities dataframe. That must mean each is repeated twice. That would mean the reason there are 1,077 observations but only 595 unique values under 'name' is that each city/town is duplicated but each county isn't.**

**Let me try to figure see if there are major differences in the rows that are duplicated out by selecting specific cities.**

In [40]:
ca_cities[ca_cities.name == 'Paradise town']

,sumlev,state,county,place,cousub,concit,primgeo_flag,funcstat,name,stname,...,popestimate2012,popestimate2013,popestimate2014,popestimate2015,popestimate2016,popestimate2017,popestimate2018,popestimate2019,popestimate042020,popestimate2020
310,162,6,0,55520,0,0,0,A,Paradise town,California,...,26036,26047,26191,26210,26289,26469,26532,4171,4294,4329
512,157,6,7,55520,0,0,1,A,Paradise town,California,...,26036,26047,26191,26210,26289,26469,26532,4171,4294,4329

**Everything looks the same other than the value under primgeo_flag.** 

**Let me try the same thing with a different city name.**

In [41]:
ca_cities[ca_cities.name == 'Palo Alto city']

,sumlev,state,county,place,cousub,concit,primgeo_flag,funcstat,name,stname,...,popestimate2012,popestimate2013,popestimate2014,popestimate2015,popestimate2016,popestimate2017,popestimate2018,popestimate2019,popestimate042020,popestimate2020
308,162,6,0,55282,0,0,0,A,Palo Alto city,California,...,66193,66982,67459,68125,68599,68513,68136,67621,67238,67008
970,157,6,85,55282,0,0,1,A,Palo Alto city,California,...,66193,66982,67459,68125,68599,68513,68136,67621,67238,67008

**That one is also the same except the primgeo_flag. According to the [data dictionary]('https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2020/sub-est2020.pdf'), this column refers to the primitive geography level.** 

**According to the Census [website]('https://www.census.gov/newsroom/blogs/random-samplings/2017/10/city_and_town_orsu.html'), the term refers to the 'smallest pieces of land that make up counties, cities and towns which cannot be further subdivided.'** 

**Let me do one more check with city that's bigger.**

In [42]:
ca_cities[ca_cities.name == 'Los Angeles city']

,sumlev,state,county,place,cousub,concit,primgeo_flag,funcstat,name,stname,...,popestimate2012,popestimate2013,popestimate2014,popestimate2015,popestimate2016,popestimate2017,popestimate2018,popestimate2019,popestimate042020,popestimate2020
241,162,6,0,44000,0,0,0,A,Los Angeles city,California,...,3847857,3877721,3904102,3933644,3957520,3975067,3981140,3982885,3976825,3970219
666,157,6,37,44000,0,0,1,A,Los Angeles city,California,...,3847857,3877721,3904102,3933644,3957520,3975067,3981140,3982885,3976825,3970219

**I feel comfortable getting rid of the duplicates after seeing that three different cities of different populations have the same numbers despite having different values under the primgeo_flag colum.**

**I'll also change the name of the 'name' column to 'city' so that it's consistent with the dataframe on mobile home spaces.**

In [43]:
ca_cities = ca_cities[ca_cities.primgeo_flag != 1]
ca_cities.rename(columns={'name':'city'}, inplace=True)
ca_cities.info()
ca_cities.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 482 entries, 1 to 482
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sumlev             482 non-null    int64
 1   state              482 non-null    int64
 2   county             482 non-null    int64
 3   place              482 non-null    int64
 4   cousub             482 non-null    int64
 5   concit             482 non-null    int64
 6   primgeo_flag       482 non-null    int64
 7   funcstat           482 non-null    object
 8   city               482 non-null    object
 9   stname             482 non-null    object
 10  census2010pop      482 non-null    object
 11  estimatesbase2010  482 non-null    int64
 12  popestimate2010    482 non-null    int64
 13  popestimate2011    482 non-null    int64
 14  popestimate2012    482 non-null    int64
 15  popestimate2013    482 non-null    int64
 16  popestimate2014    482 non-null    int64
 17  popestimate2015    482 non-null    int64
 18  popestimate2016    482 non-null    int64
 19  popestimate2017    482 non-null    int64
 20  popestimate2018    482 non-null    int64
 21  popestimate2019    482 non-null    int64
 22  popestimate042020  482 non-null    int64
 23  popestimate2020    482 non-null    int64
dtypes: int64(20), object(4)
memory usage: 94.1+ KB

,sumlev,state,county,place,cousub,concit,primgeo_flag,funcstat,city,stname,...,popestimate2012,popestimate2013,popestimate2014,popestimate2015,popestimate2016,popestimate2017,popestimate2018,popestimate2019,popestimate042020,popestimate2020
1,162,6,0,296,0,0,0,A,Adelanto city,California,...,31222,31414,32745,33376,33484,34309,34411,34506,34540,34537
2,162,6,0,394,0,0,0,A,Agoura Hills city,California,...,20484,20537,20585,20634,20586,20471,20307,20103,19954,19881
3,162,6,0,562,0,0,0,A,Alameda city,California,...,75750,76616,77646,78997,80023,80178,80196,79813,79170,78841
4,162,6,0,674,0,0,0,A,Albany city,California,...,19041,19286,19557,19827,19958,20168,20352,20257,20110,20031
5,162,6,0,884,0,0,0,A,Alhambra city,California,...,84006,84305,84635,85086,85341,85270,84666,83932,83502,83261

**So that I'm able to merge with the other dataframe, I'll also remove the 'city' and 'town' substrings that come after each entry.**

In [44]:
ca_cities['city'] = ca_cities['city'].str.replace(' city','')

In [45]:
ca_cities['city'] = ca_cities['city'].str.replace(' town', '')

**I want to look specifically at the 2018 population estimate, because any year thereafter will take into account the population exodus that happened in Paradise after the fire.**

In [46]:
ca_cities_2018_pop = ca_cities[['city',
                            'popestimate2018']]

In [47]:
ca_cities_2018_pop

             city  popestimate2018
1        Adelanto            34411
2    Agoura Hills            20307
3         Alameda            80196
4          Albany            20352
5        Alhambra            84666
..            ...              ...
478    Yountville             3002
479         Yreka             7594
480     Yuba City            66654
481       Yucaipa            54482
482  Yucca Valley            21730

[482 rows x 2 columns]

**Export the dataframe to my processed directory.**

In [48]:
outname = 'ca_cities_2018_analysis.csv'
fullname = os.path.join(processed_outdir, outname)
ca_cities_2018_pop.to_csv(fullname)

**UPDATE MAY 5: I'm going to scratch the above. I spoke with someone from the Census bureau. After I described the project and the issues I was having with losing a lot of cities in the merge, he recommended using the ACS 2018 5-year estimates because it goes down to smaller population levels than the population estimates dataset.**

In [73]:
def get_ACS(year):
    dsource = 'acs'
    dname = 'acs5'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}/profile'
    chart = 'DP05_0001E'
    state = '06'
    api_key = os.environ["CENSUS_API_KEY"]
    data_url = f'{base_url}?get=NAME,{chart}&for=place:*&in=state:{state}&key={api_key}'
    response=requests.get(data_url)
    json=response.json()
    return json

#https://api.census.gov/data/2020/acs/acs5/profile?get=NAME,DP02_0001E&for=place:*&in=state:*&key=YOUR_KEY_GOES_HERE

In [74]:
population_by_place = get_ACS(2018)

In [77]:
population_place_2018 =pd.DataFrame(population_by_place[1:], columns=population_by_place[0]
                              ).rename(columns={'NAME':'city',
                                                'DP05_0001E':'pop_2018_est'}
                                      ).drop(columns=['state',
                                                      'place']
                                            )#first argument specified rows, second specifies columns

In [83]:
population_place_2018.head(200)

                                  city pop_2018_est
0                          Mead Valley        19925
1                             Meridian          405
2                           Mesa Verde          584
3                       Mexican Colony          363
4                             Midpines         1396
5                          Midway City         8374
6                              Milford          181
7                              Minkler         1074
8                              Miranda          672
9                             Monmouth          103
10                           Mono City           98
11                              Monson          380
12                             Maywood        27542
13                            Monrovia        37006
14                            Palmdale       156904
15                         Quartz Hill        10164
16                       Redondo Beach        67700
17                          San Marino        13285
18                    Santa Fe Springs        17791
19                        Sierra Madre        11006
20                     Manhattan Beach        35573
21                          San Rafael        58939
22                       Santa Venetia         4790
23                           Sausalito         7139
24                       Stinson Beach          556
25                            Bootjack          768
26                             Hayfork         2421
27                            Lewiston         1340
28                            Beaumont        45403
29                       Bermuda Dunes         6817
30                             Rocklin        63127
31                             Grayson         1224
32                               Keyes         6185
33                            Corcoran        22301
34                           Stratford          878
35                        Laguna Hills        31185
36                             Alpaugh         1074
37                        Farmersville        10742
38                          Strathmore         2915
39                             Visalia       131066
40                        Laguna Woods        16228
41                            La Habra        61910
42                          Seal Beach        24364
43                          Villa Park         5912
44                        Meadow Vista         3460
45                             Hayward       158241
46                           Livermore        89027
47                         Lemon Grove        26767
48   Fetters Hot Springs-Agua Caliente         4697
49                          Healdsburg        11802
50                            Petaluma        60635
51                             Mineral          292
52                           Red Bluff        14132
53                         Laytonville         1175
54                     Montalvin Manor         3023
55                 Monterey Park Tract          291
56                      Monument Hills         1700
57                    Moskowite Corner          151
58                     Mountain Center            0
59                       Mountain Gate          794
60                      Mountain House        15645
61                        Mount Hermon          998
62                        Mount Laguna            0
63                          Myers Flat            0
64                           Newcastle         1167
65                          New Cuyama          763
66                              Newell          342
67                      New Pine Creek           71
68                             Nicasio          106
69                            Nicolaus          166
70                        Nipinnawasee          319
71                                Nord          426
72                       Norris Canyon          987
73                          North Gate          559
74                      North Richmond         4233
75                           Elk Grove       168503
76                     El Dorado Hills        45599
77                          West Point          571
78                       Mountain View        80993
79                             Bonsall         4464
80                         Lake Forest        82911
81                           Santa Ana       333499
82                             Lemoore        25791
83                Poplar-Cotton Center         2436
84                            La Presa        37437
85                         Los Molinos         1845
86                        Agoura Hills        20636
87                           Mendocino          782
88                            Eldridge         1351
89                              Duarte        21713
90                          Fort Bragg         7298
91                        Solana Beach        13370
92                       Rolling Hills         1630
93                            Whittier        86523
94                      North El Monte         4028
95                          Cherryland        16387
96                     Shingle Springs         3865
97                    South Lake Tahoe        21814
98                           Lockeford         3390
99                              Morada         4068
100                           Stockton       306283
101                           Lakeport         4855
102                            Leggett           62
103                         Lemon Hill        14096
104                       Leona Valley         1581
105                             Likely            0
106                           Lindcove          438
107                       Linnell Camp          686
108                         Litchfield          178
109                       Little River          189
110                          Hollister        37835
111                            Artesia        16817
112                              Azusa        49544
113                       Baldwin Park        76222
114                           Cerritos        50172
115                           Commerce        12933
116                       Hidden Hills         1634
117                           Industry          344
118                          Inglewood       110327
119                             Lennox        21329
120                          Canyondam           66
121                     Crescent Mills          287
122                           La Porte            0
123                Little Grass Valley            0
124                       Mohawk Vista           63
125                       Chinese Camp          206
126                 West Puente Valley        23629
127                             Colusa         5902
128                     Forest Meadows         1516
129                         El Cerrito         5471
130                Idyllwild-Pine Cove         2459
131                        Winterhaven          210
132                         Chowchilla        18533
133                          Parksdale         2493
134                     Cathedral City        54037
135                          Highgrove         4986
136                            Lindsay        13232
137                           Woodside         5541
138                       Buttonwillow         1591
139                            Banning        30942
140                           Calimesa         8651
141                       Home Gardens        11442
142                            Brawley        26009
143                          El Centro        43898
144                          Holtville         6458
145                           Imperial        17175
146                            Lucerne         2956
147                     North Lakeport         3141
148                  Lake of the Pines         4137
149                            Truckee        16377
150                       Dillon Beach          219
151                           Romoland         2227
152                              Indio        88291
153                           Murrieta       111427
154                     Thousand Palms         7814
155                           Calexico        39934
156                      Desert Shores          619
157                           Ocotillo           58
158                            Bolinas         1077
159                       Corte Madera         9866
160                            Bodfish         1384
161                             Delano        52713
162              Channel Islands Beach         2864
163                       Golden Hills         9407
164                              Keene          313
165                         Lost Hills         1943
166                           Lockwood          604
167                             Lodoga          126
168                             Loleta          676
169                           Loma Mar          114
170                             Elmira          285
171                          Rio Vista         8618
172                            Vallejo       120977
173                            Burbank         5252
174                             Colfax         2029
175                        San Joaquin         4021
176                        Shaver Lake          498
177                          Alum Rock        11791
178                          Fruitdale          899
179                          Los Altos        30588
180                           Milpitas        77457
181                        Morgan Hill        43876
182                            Magalia        12671
183                           Paradise        26543
184                            Willits         4893
185                    West Menlo Park         4116
186                Bear Valley Springs         5442
187                          Montecito         8611
188                        Toro Canyon         1735
189                           Big Pine         1568
190                       Round Valley          533
191                        West Bishop         2661
192                          Wilkerson          431
193                            Almanor            0
194          Lake Almanor Country Club          302
195                             Madera        64362
196                         Muir Beach          242
197                             Novato        55523
198                           Mariposa         1351
199                       Cameron Park        19902

In [81]:
population_place_2018['city'] = population_place_2018['city'].str.replace(' city','')
population_place_2018['city'] = population_place_2018['city'].str.replace(' CDP','')
population_place_2018['city'] = population_place_2018['city'].str.replace(' town','')
population_place_2018['city'] = population_place_2018['city'].str.replace(', California','')

In [84]:
outname = 'ca_cities_2018_ACS.csv'
fullname = os.path.join(processed_outdir, outname)
population_place_2018.to_csv(fullname)

### Merging

**In the following steps, I'll do a left join on the ACS estimates and the MH dataframe on the common column of 'city.' Then I'll export this into my processed data directory.**

In [85]:
merged = pd.merge(population_place_2018, list_of_parks_analysis, how='left', on=['city', 'city'])

In [86]:
pd.set_option('display.max_rows', 500)

In [87]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1521 entries, 0 to 1520
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          1521 non-null   object
 1   pop_2018_est  1521 non-null   object
 2   mh_spaces     678 non-null    float64
dtypes: float64(1), object(2)
memory usage: 47.5+ KB

In [88]:
merged

                city pop_2018_est  mh_spaces
0        Mead Valley        19925        NaN
1           Meridian          405        6.0
2         Mesa Verde          584        NaN
3     Mexican Colony          363        NaN
4           Midpines         1396       11.0
...              ...          ...        ...
1516   Beverly Hills        34362        NaN
1517          Covina        48403      884.0
1518        Del Aire        10065        NaN
1519          Downey       112901      190.0
1520        Glendale       200372        NaN

[1521 rows x 3 columns]

In [89]:
outname = 'merged.csv'
fullname = os.path.join(processed_outdir, outname)
merged.to_csv(fullname)